Adds support for the AudioInjector.net Octo sound card.
raspberrypi/linux pull request #1849
Opened 2017-02-18 11:06 UTC by flatmax

Contains the sound/soc/bcm ALSA machine driver and necessary alterations
to the Kconfig and Makefile. Adds the dts overlay and updates the Makefile
and README.
Updates the relevant defconfig files to enable building for the Raspberry Pi.

2017-02-24 21:55 UTC, pelwell requested changes
I've made a few largely nit-picky comments. The biggest issue is that this PR is against 4.4 and we've now moved to 4.9 (sorry about the review delay).

If you fix the nits I can merge against 4.4 and then cherry-pick onto 4.9, or you can go straight to 4.9.

2017-02-24 21:55 UTC, pelwell commented on sound/soc/bcm/audioinjector-octo-soundcard.c
> +  return snd_soc_dai_set_bclk_ratio(rtd->cpu_dai, 64);
Stick to the Linux indentation rules - hard TAB characters, set to 8 characters.

2017-02-24 21:55 UTC, pelwell commented on sound/soc/bcm/audioinjector-octo-soundcard.c
> +
Delete this trailing blank line.

2017-02-24 21:55 UTC, pelwell commented on sound/soc/bcm/audioinjector-octo-soundcard.c
> +
Delete this trailing blank line.

2017-02-24 21:55 UTC, pelwell commented on arch/arm/boot/dts/overlays/Makefile
> +dtbo-$(RPI_DT_OVERLAYS) += audioinjector-addons.dtbo
I know it's picky, but can you put this in front of the previous line (in lexicographic order).

2017-02-24 21:55 UTC, pelwell commented on arch/arm/boot/dts/overlays/README
> +Name:   audioinjector-addons
Order, again.

2017-02-24 21:55 UTC, pelwell commented on arch/arm/boot/dts/overlays/audioinjector-addons-overlay.dts
> +      mult-gpios = <&gpio 27 0>, <&gpio 22 0>, <&gpio 23 0>;
Indentation.

2017-02-26 00:34 UTC, flatmax commented
Hey Phil,

I think it will be easiest if I kill this pull request. I will switch to 
the 4.9 branch and run check_patch.pl on my changes before submitting - 
apologies for not doing that in the first place.

Matt


On 25/02/17 08:55, Phil Elwell wrote:
>
> *@pelwell* requested changes on this pull request.
>
> I've made a few largely nit-picky comments. The biggest issue is that 
> this PR is against 4.4 and we've now moved to 4.9 (sorry about the 
> review delay).
>
> If you fix the nits I can merge against 4.4 and then cherry-pick onto 
> 4.9, or you can go straight to 4.9.
>
> ------------------------------------------------------------------------
>
> In sound/soc/bcm/audioinjector-octo-soundcard.c 
> <https://github.com/raspberrypi/linux/pull/1849#discussion_r103039490>:
>
> > +
> +#include <linux/module.h>
> +#include <linux/types.h>
> +#include <linux/gpio/consumer.h>
> +
> +#include <sound/core.h>
> +#include <sound/soc.h>
> +#include <sound/pcm_params.h>
> +#include <sound/control.h>
> +
> +static struct gpio_descs *mult_gpios;
> +static unsigned int audioinjector_octo_rate;
> +
> +static int audioinjector_octo_soundcard_dai_init(struct snd_soc_pcm_runtime *rtd)
> +{
> +  return snd_soc_dai_set_bclk_ratio(rtd->cpu_dai, 64);
>
> Stick to the Linux indentation rules - hard TAB characters, set to 8 
> characters.
>
> ------------------------------------------------------------------------
>
> In sound/soc/bcm/audioinjector-octo-soundcard.c 
> <https://github.com/raspberrypi/linux/pull/1849#discussion_r103040243>:
>
> > +				dev_err(&pdev->dev, "Property 'codec' missing or invalid\n");
> +				return -EINVAL;
> +			}
> +
> +	}
> +
> +	if ((ret = snd_soc_register_card(card)))
> +		dev_err(&pdev->dev, "snd_soc_register_card failed (%d)\n", ret);
> +	return ret;
> +}
> +
> +static int audioinjector_octo_soundcard_remove(struct platform_device *pdev)
> +{
> +	struct snd_soc_card *card = platform_get_drvdata(pdev);
> +	return snd_soc_unregister_card(card);
> +
>
> Delete this trailing blank line.
>
> ------------------------------------------------------------------------
>
> In sound/soc/bcm/audioinjector-octo-soundcard.c 
> <https://github.com/raspberrypi/linux/pull/1849#discussion_r103040329>:
>
> > +static struct platform_driver audioinjector_octo_soundcard_driver = {
> +       .driver         = {
> +		.name   = "audioinjector-audio",
> +		.owner  = THIS_MODULE,
> +		.of_match_table = audioinjector_octo_soundcard_of_match,
> +       },
> +       .probe          = audioinjector_octo_soundcard_probe,
> +       .remove         = audioinjector_octo_soundcard_remove,
> +};
> +
> +module_platform_driver(audioinjector_octo_soundcard_driver);
> +MODULE_AUTHOR("Matt Flax <flatmax@flatmax.org>");
> +MODULE_DESCRIPTION("AudioInjector.net octo Soundcard");
> +MODULE_LICENSE("GPL v2");
> +MODULE_ALIAS("platform:audioinjector-octo-soundcard");
> +
>
> Delete this trailing blank line.
>
> ------------------------------------------------------------------------
>
> In arch/arm/boot/dts/overlays/Makefile 
> <https://github.com/raspberrypi/linux/pull/1849#discussion_r103040565>:
>
> > @@ -19,6 +19,7 @@ dtbo-$(RPI_DT_OVERLAYS) += akkordion-iqdacplus.dtbo
>   dtbo-$(RPI_DT_OVERLAYS) += allo-piano-dac-pcm512x-audio.dtbo
>   dtbo-$(RPI_DT_OVERLAYS) += at86rf233.dtbo
>   dtbo-$(RPI_DT_OVERLAYS) += audioinjector-wm8731-audio.dtbo
> +dtbo-$(RPI_DT_OVERLAYS) += audioinjector-addons.dtbo
>
> I know it's picky, but can you put this in front of the previous line 
> (in lexicographic order).
>
> ------------------------------------------------------------------------
>
> In arch/arm/boot/dts/overlays/README 
> <https://github.com/raspberrypi/linux/pull/1849#discussion_r103040613>:
>
> > @@ -273,6 +273,12 @@ Load:   dtoverlay=audioinjector-wm8731-audio
>   Params: <None>
>   
>   
> +Name:   audioinjector-addons
>
> Order, again.
>
> ------------------------------------------------------------------------
>
> In arch/arm/boot/dts/overlays/audioinjector-addons-overlay.dts 
> <https://github.com/raspberrypi/linux/pull/1849#discussion_r103040731>:
>
> > +				status = "okay";
> +			};
> +
> +			cs42448_mclk: codec-mclk {
> +				compatible = "fixed-clock";
> +				#clock-cells = <0>;
> +				clock-frequency = <49152000>;
> +			};
> +		};
> +	};
> +
> +	fragment@2 {
> +		target = <&sound>;
> +		__overlay__ {
> +			compatible = "ai,audioinjector-octo-soundcard";
> +      mult-gpios = <&gpio 27 0>, <&gpio 22 0>, <&gpio 23 0>;
>
> Indentation.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/raspberrypi/linux/pull/1849#pullrequestreview-23818973>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/AAq6B-7teKfsp-5h7cfqZwH5dW1lK4qyks5rf1HKgaJpZM4MFFiG>.
>

2017-05-22 08:27 UTC, pelwell commented
Resubmitted and merged as #1883.

2017-05-22 08:27 UTC, closed without merging