Rpi 4.12.y
raspberrypi/linux pull request #2153
Opened 2017-08-07 13:40 UTC by VT-Github-Raspberrypi

ARM64: bcm2837: enable sdhost in device tree for the
Raspberry Pi 3
branch rpi-4.12.y

Fix for https://github.com/raspberrypi/linux/issues/2151

Signed-off-by: VT-Github-Raspberrypi <github.raspberrypi@votarytech.com>

2017-08-07 13:41 UTC, VT-Github-Raspberrypi reviewed
It looks good to me.

2017-08-07 13:44 UTC, pelwell commented
![screenshot](https://user-images.githubusercontent.com/8911409/29029215-d5857092-7b7e-11e7-959f-3177072e28cd.png)
Really?

2017-08-07 13:44 UTC, pelwell commented
And when you fix it, please give your commit a proper name - Rpi 4.12.y isn't very descriptive.

2017-08-07 14:36 UTC, VT-Github-Raspberrypi commented
Updated commit message as per review comment by pelwell.

2017-08-08 13:48 UTC, VT-Github-Raspberrypi commented
Follow these steps for RPI-3 64bit boot up.
https://github.com/raspberrypi/linux/wiki/config.txt

2017-08-09 07:48 UTC, VT-Github-Raspberrypi reviewed
It looks good to me.

2017-08-09 09:07 UTC, VT-Github-Raspberrypi reviewed
It looks good to me.

2017-08-09 09:22 UTC, pelwell requested changes

2017-08-09 09:22 UTC, pelwell commented on arch/arm/boot/dts/bcm2835-rpi.dtsi
> +
This is an upstream file - please don't modify it, except by trying to push changes upstream.

Downstream DT has a framebuffer node in bcm2708-rpi.dtsi.

2017-08-09 09:22 UTC, pelwell commented on arch/arm64/boot/dts/broadcom/bcm2837-rpi-3-b.dts
> +
This is also an upstream file. Have you considered using bcm2710-rpi-3-b.dts instead?

2017-08-09 12:08 UTC, VT-Github-Raspberrypi commented
Now reverted frambuffer changes.

2017-08-09 12:13 UTC, VT-Github-Raspberrypi reviewed
Now seems all fine.

2017-08-09 12:19 UTC, pelwell commented
bcm2837-rpi-3-b.dts is also an upstream file. Have you considered using bcm2710-rpi-3-b.dts instead?

2017-08-09 12:31 UTC, VT-Github-Raspberrypi commented
Yes. We only used bcm2837-rpi-3-b.dts.

2017-08-09 12:36 UTC, pelwell commented
And I'm saying that I won't accept changes to that file. Try using bcm2710-rpi-3-b.dts instead.

2017-08-09 13:14 UTC, VT-Github-Raspberrypi commented
Without this changes Pi-3 board doesn't boot up using bcm2837 dts. 
As per your suggestion like ,"use bcm2710 dts" then What is the use for bcm2837 dts ?.

We have been using bcm2837 dts and making changes according to considering SOC(BCM2837)  raspberry pi-3 64bit.

2017-08-09 13:20 UTC, pelwell commented
bcm2837-rpi-3-b.dts is the official upstream Linux support for Pi3 (64-bit, in this case). Upstream changes happen slowly, and they don't support overlays etc., but you can get the source from kernel.org.

bcm2710-rpi-3-b.dts is the downstream Pi3 support, although we don't officially support 64-bit ourselves. Downstream changes can be very quick, but there is likely to be more churn than you get with upstream-only builds.

2017-08-09 13:34 UTC, VT-Github-Raspberrypi commented
My changes are on upstream file bcm2837 then what is the reason for not accepting my changes ?.

Let me clear that , What should i do for my changes to be get merged on kernel-4.12.y ?

2017-08-09 13:38 UTC, pelwell commented
Changes to upstream files should be submitted as patches via email to the Linux maintainers. There is a guide to the process here: https://www.kernel.org/doc/html/v4.12/process/submitting-patches.html

2017-08-09 13:49 UTC, VT-Github-Raspberrypi commented
What should i do for my changes to be get merged on https://github.com/raspberrypi/linux/tree/rpi-4.12.y ? . 
same proccess ?.

2017-08-09 13:53 UTC, pelwell commented
Once it is accepted upstream (which could be to a 4.13 release candidate, but any branch will do) we can cherry-pick it back to rpi-4.12.y.

2017-08-12 06:52 UTC, lategoodbye commented
Please look at my comments in #2151 . This change can't be accepted in upstream because it's already there in 4.13.

2017-12-05 14:55 UTC, pelwell commented
Closing as the next RPi kernel version will be 4.14.

2017-12-05 14:55 UTC, closed without merging