Add device tree overlay for HD44780
raspberrypi/linux pull request #2589
Opened 2018-06-24 16:33 UTC by jboomer

Added a device tree overlay for an HD44780 compatible LCD

2018-06-29 10:04 UTC, pelwell requested changes
Sorry for the review delay - this one slipped under the radar.

Apart from the compatible string, I think you could shorten the parameter names - they don't need the `lcd_` prefix - but I leave the decision to you.

Also note that this overlay won't be much use until the driver module is enabled in the defconfigs.

Otherwise this looks good.

2018-06-29 10:04 UTC, pelwell commented on arch/arm/boot/dts/overlays/hd44780-lcd-overlay.dts
> +    compatible = "brcm, bcm2708";
Although in practice this string isn't checked, it should at least be one of the recognised strings. These days I would just use: "brcm,bcm2835" (note the lack of a space after the comma).

2018-06-29 12:08 UTC, jboomer commented
> Sorry for the review delay - this one slipped under the radar.

No problem!

> Also note that this overlay won't be much use until the driver module is enabled in the defconfigs.

I know, it will be useful for people compiling their own kernel I guess. If it is included, I guess the dtbo will also be added to the firmware repo?

> I think you could shorten the parameter names

Won't this potentially clash with other parameter names? Or if there are two overlays with a 'pin' parameter and config.txt contains:

```
dtoverlay=first-overlay`
dtparam=pin=1
dtoverlay=second-overlay
dtparam=pin=2

```
, will the kernel know which one applies to which overlay?

I will add the fixes later this weekend

2018-06-29 12:26 UTC, pelwell commented
> I know, it will be useful for people compiling their own kernel I guess.

That's fine, but if you did want those options (CONFIG_AUXDISPLAY=y and CONFIG_HD44780=m) setting as standard then they would only add two modules of 15kB and 10kB...)

> If it is included, I guess the dtbo will also be added to the firmware repo?

Yes, of course.

> Won't this potentially clash with other parameter names?

No. The parameters declared by an overlay go out of scope at the next `dtoverlay` directive. The worst that can happen is that they mask a parameter of the base .dtb, in which case you can force the scope to close with an empty `dtoverlay=` line. The corollary of this is that until the next `dtoverlay` directive the parameters remain in scope, meaning that the parameters to an overlay can be split across multiple lines as you have above, rather than the more concise version which is also supported:
```
dtoverlay=first-overlay,pin=1
dtoverlay=second-overlay,pin=2
```

2018-06-30 12:42 UTC, jboomer commented
Added requested changes, would you want the changes (enable hd44780 module) to defconfig in a separate PR or should I put it here as well?

2018-06-30 12:45 UTC, pelwell commented
A separate commit would make it easier in the future - when we jump kernel versions the config commits get squashed into a single commit, and the DT commits into another.

2018-06-30 12:46 UTC, pelwell commented
P.S. check the indentation in the README - it looks like it's changed and the parser is very picky and dumb.

2018-07-02 17:18 UTC, jboomer commented
Fixed the indentation and added changes to defconfig in a separate commit.

2018-07-02 19:39 UTC, pelwell commented
Thanks. I've added the options to the bcm2709_defconfig as well, squashed it all down to two commits and applied them via the command line tools.

2018-07-02 19:39 UTC, closed without merging