bcm2835-mmc: Fix DMA channel leak
raspberrypi/linux pull request #2816
Opened 2019-01-18 11:50 UTC by l1k

The BCM2835 MMC host driver requests a DMA channel on probe but neglects
to release the channel in the probe error path and on driver unbind.

I'm seeing this happen on every boot of the Compute Module 3: On first
driver probe, DMA channel 2 is allocated and then leaked with a "could
not get clk, deferring probe" message. On second driver probe, channel 4
is allocated.

Fix it.

Signed-off-by: Lukas Wunner <lukas@wunner.de>
Cc: @pavlic244

2019-01-18 18:19 UTC, lategoodbye commented
Nice catch. It looks like the that irq isn't freed in case bcm2835_mmc_add_host() fails.

Btw upstream bcm2835.c is also affect :-(

2019-01-18 18:27 UTC, l1k commented
Ok I can see to it that I fix it in the upstream driver as well. That one is actually for the other interface (the non-Arasan one), curious that it has the same issue.

2019-01-18 18:40 UTC, lategoodbye commented
After this pull request has been merge, i will prepare patches to fix the missing return code handling of mmc_of_parse().

Similiar to this:
https://patchwork.kernel.org/patch/10741805/

2019-01-19 16:06 UTC, l1k commented
Further scrutiny has revealed more issues in the probe/remove routines of the downstream Arasan driver and I've updated this pull to address them. I've also posted the DMA channel leak for the upstream non-Arasan driver to the list, together with a bunch of cleanups. So far this is all compile-tested only, I won't be able to test on real hardware before returning to the office on Tuesday. Stefan, would you be able to give the two series a whirl? Thanks!

2019-01-20 16:01 UTC, lategoodbye commented
@l1k I'm busy with the pull requests for Linux 5.1, but i try to take a look at them. Please always add a note (e.g. in the cover letter) in case a patch is only compile tested. Because as a maintainer i assume all patches has been tested with at least 1 platform before submission.

2019-01-22 08:17 UTC, lategoodbye requested changes
I prefer to drop free_irq() instead. Or do you see a problem with the device managed interrupt?

2019-01-22 09:35 UTC, l1k commented
I don't think dropping free_irq() is an option. As I've explained in the commit message, invocation of the interrupt handler needs to be avoided after driver structures have been torn down. If the interrupt is device-managed, it won't be freed until `bcm2835_mmc_remove()` has finished and that function frees the `struct mmc_host` and `struct bcm2835_host`, which are accessed in the hardirq and threaded interrupt handler, potentially leading to a use-after-free. Note that it's not sufficient to quiesce the interrupt at the hardware level because the interrupt is requested with `IRQF_SHARED`, so it's possible that the handler runs if an interrupt for another device is signaled which shares the interrupt. (It's not clear to me from the datasheet which other devices share the interrupt. According to `Documentation/devicetree/bindings/interrupt-controller/brcm,bcm2835-armctrl-ic.txt`, bank 2 interrupt 30 is used by `VC_ARASANSDIO`, no word about devices sharing the interrupt. Maybe `IRQF_SHARED` isn't really needed here, but independently, freeing the interrupt after driver structures have been torn down seems unnecessarily risky. Big no-no.)

2019-01-22 10:01 UTC, lategoodbye commented
Thanks for the explanation. Yes, the IRQF_SHARED is also wrong to me, because no other driver should use it. But changing from devm_request_threaded_irq to request_threaded_irq isn't sufficient in your commit. You will need to call free_irq in all error cases after the irq has been requested.

2019-01-22 11:00 UTC, l1k commented
Huh? There *are* no error cases after the IRQ has been requested: `bcm2835_mmc_add_host()` contains no further error checks after the call to `request_threaded_irq()` and `bcm2835_mmc_add_host()` is the last function called by `bcm2835_mmc_probe()` which might fail.

The call to `mmc_add_host()` is not error checked at the moment, it should be and *then* would a `free_irq()` be necessary in an error path. However, the question is how much time should be wasted fixing this driver's bugs. There's also deadlocks in the reset code. Upstream uses `sdhci-iproc.c` but doesn't support DMA. What's the plan? Add DMA to `sdhci-iproc.c` and scrap this driver? Why is the upstream SD host driver so similar to the downstream Arasan driver, what's the history here?

2019-01-22 12:09 UTC, lategoodbye commented
Sorry, i confuse it with bcm2835 sdhost.

AFAIK the Arasan core of the BCM2835 doesn't support DMA according to SDHCI spec. So DMA implementation could be a hassle. I didn't invest any time to estimate the possible effort. But it was my proposal to drop the old bcm2835-mmc (which also didn't support DMA) in upstream and to use sdhci-iproc instead.

The upstream bcm2835 sdhost was derived from an older version of the downstream bcm2835 sdhost. But didn't know the history of the downstream ones.

2019-01-22 15:35 UTC, l1k commented
I've amended this pull with a commit to handle errors occurring in `bcm2835_mmc_add_host()` and successfully tested both the series contained herein as well as the one for the upstream sdhost driver (which I've submitted to the list), so this pull is ready to go in from my POV. Thanks.

2019-01-22 15:57 UTC, lategoodbye commented
Thank you, i'm fine with this pull request.

2019-02-10 17:06 UTC, lategoodbye commented
In the meantime the upstream patches has been merged.

2019-02-11 11:20 UTC, l1k commented
Right, however those were for the upstream sdhost driver. The present pull is for the downstream Arasan driver (which isn't present in upstream). (Just in case this wasn't clear already.)

2019-02-17 15:22 UTC, merged

2019-03-25 07:23 UTC, l1k commented
@pelwell: These patches are missing on the rpi-4.19.y branch. Should I send another pull or can you cherry-pick them? Thanks!

2019-03-25 08:57 UTC, pelwell commented
They're cherry-picked now.