add Hifiberry DAC+DSP soundcard driver
raspberrypi/linux pull request #3224
Opened 2019-09-11 15:25 UTC by j-schambacher

new driver to be used instead of DAC-only driver to allow capture and playback (depending on DSP firmware capabilities).

2019-09-11 16:05 UTC, pelwell requested changes
@hifiberry Is this an official driver?

Please squash these commits down to 1, generate a patch file (`git format-patch HEAD^` should work after squashing) and run `scripts/checkpatch.pl` on it - you'll find lots of whitespace and other formatting errors. Once you've got it to the point that checkpatch is only complaining about the lack of documentation of compatible strings, use `git push -f` to update your PR.

2019-09-11 16:05 UTC, pelwell commented on arch/arm/boot/dts/overlays/hifiberry-dspdac-overlay.dts
> +	compatible = "brcm,bcm2708";
Please use "brcm,bcm2835" from now on, unless it is Pi4-specific in which case use "brcm,bcm2838".

2019-09-11 16:08 UTC, hifiberry commented
@pelwell Yes this is "official".

2019-09-11 18:21 UTC, j-schambacher commented
something went completely wrong with my repo.. still not the version I want ....let you know when I've fixed it...sorry

2019-09-11 18:28 UTC, pelwell commented
Take your time. By the way, `git rebase -i HEAD~n` is a very useful command for tidying up commits, if you haven't come across it before.

2019-09-11 18:29 UTC, pelwell commented
Oh - and a comment when you're done helps because we don't often get notifications of pushes.

2019-09-12 09:57 UTC, j-schambacher commented
@pelwell done the requested fixes and changes. I hope it's ok now to merge.

2019-09-12 12:57 UTC, pelwell commented
This is a completely passive board - there are no controls, it just adapts to the clock and sample sizes used by the CPU - so I suspect the codec driver is unnecessary and the card driver could be replaced with simple-card, but I don't have time to investigate further.

2019-09-12 12:57 UTC, merged

2019-09-12 13:09 UTC, j-schambacher commented
@pelwell you are right, that's why I integrated it into the simple-card drivers. But so far the set does not contain a simple capture AND play without controls. A generically named copy of it may be a solution, but for now we want to keep the hifiberry specific name to allow potential HW tweaks like REST via GPIO.

2019-09-12 13:09 UTC, j-schambacher commented
@pelwell and thanks for all!