overlays: add wm8960-soundcard overlay
raspberrypi/linux pull request #4039
Opened 2021-01-02 02:38 UTC by shawaj

add overlay for waveshare wm8960 simple-audio-card

Change-type: patch
Signed-off-by: Aaron Shaw <shawaj@gmail.com>

2021-01-02 02:39 UTC, shawaj commented
FYI - in the readme I left the description for the `master` override as unsure of function - because I wasn't sure what it actually does.

2021-01-05 16:54 UTC, pelwell requested changes
You need to understand and explain what the "master" parameter is doing - it looks wrong to me because if set to "on" it enables fragment 2 and disables fragment 3, and if "off" it disables fragment 2 and enables fragment 3, and yet both fragments are enabled by default.

2021-01-05 16:54 UTC, pelwell commented on arch/arm/boot/dts/overlays/README
> +Name:   wm8960-soundcard
Alphabetical order, please.

2021-01-05 16:54 UTC, pelwell commented on arch/arm/boot/dts/overlays/Makefile
> +	wm8960-soundcard.dtbo \
"wm" comes after "wi".

2021-01-05 16:54 UTC, pelwell commented on arch/arm/boot/dts/overlays/wm8960-soundcard-overlay.dts
> +	compatible = "brcm,bcm2708";
Please use `"brcm,bcm2835"`.

2021-01-05 16:54 UTC, pelwell commented on arch/arm/boot/dts/overlays/wm8960-soundcard-overlay.dts
> +
Delete this blank line.

2021-01-05 16:54 UTC, pelwell commented on arch/arm/boot/dts/overlays/wm8960-soundcard-overlay.dts
> +			wm8960: wm8960{
There should be a space before the brace.

2021-01-07 18:11 UTC, shawaj commented on arch/arm/boot/dts/overlays/Makefile
> +	wm8960-soundcard.dtbo \
doh! my bad 🤦‍♂️

2021-01-07 18:16 UTC, shawaj commented
@pelwell have updated the PR. As far as I can tell - the master override is not needed. I can't find anything in the docs for the board about using it or anything like that so I also agree that it is wrong, certainly for this board. Perhaps it is used for some other hardware that I am not aware of, but I can't see any function for it either.

2021-01-07 21:16 UTC, merged

2021-01-07 21:16 UTC, pelwell commented
You can always add it later if a use becomes apparent.

2021-01-07 22:30 UTC, shawaj commented
agreed, thanks @pelwell

2021-04-05 11:52 UTC, tewarid commented
Thanks for adding this. It works with Seeed's [ReSpeaker 2-Mics Pi HAT](http://wiki.seeedstudio.com/ReSpeaker_2_Mics_Pi_HAT/) after enabling a few switches that are off, and adjusting the volume

```bash
amixer -c1 sset 'Left Input Mixer Boost' toggle
amixer -c1 sset 'Left Output Mixer PCM' toggle
amixer -c1 sset 'Right Input Mixer Boost' toggle
amixer -c1 sset 'Right Output Mixer PCM' toggle
amixer -c1 sset 'Headphone',0 100%,100%
```

I am, however, getting very noisy sound capture using

```bash
arecord -f cd -Dhw:1 -d5 > test.wav
```

Please see [test.wav.zip](https://github.com/raspberrypi/linux/files/6257795/test.wav.zip).

I don't get that when using the [Seeed's official soundcard driver](https://github.com/respeaker/seeed-voicecard). I've compared alsa settings and they look all right to my, untrained, eyes. See  [asound.state.txt](https://github.com/raspberrypi/linux/files/6257874/asound.state.txt) and [seeed-asound.state.txt](https://github.com/raspberrypi/linux/files/6257875/seeed-asound.state.txt).

2026-09-21 07:41 UTC, meiser79 commented
Hi,

this overlay needs an update, see https://github.com/jxlarrea/kiosk-satellite/issues/563#issuecomment-5750401495

Regards,
meiser79