overlays: gpio-led: new overlay
raspberrypi/linux pull request #4206
Opened 2021-03-12 07:19 UTC by agordon

Add generic connection between the kernel's LED framework and
RPI's GPIO pins.

Signed-off-by: Assaf Gordon <assafgordon@gmail.com>

2021-03-12 07:22 UTC, agordon commented
Hello RPI developers,

I'd like to suggest the following small addition to the RPI's overlays: the ability to connect a LED to any output GPIO. Similar to `gpio-key` in nature, with the advantage of using the kernel's LED system, so able to connect a LED to a kernel trigger (e.g. cpu load / heartbeat / panic / etc ).
(I'm not a kernel developer, and I'm happy to adjust if needed to suit the coding style - let me know.)

2021-03-12 08:47 UTC, pelwell requested changes
What a coincidence - I was thinking about adding a similar overlay only yesterday in response to a Forum post: https://www.raspberrypi.org/forums/viewtopic.php?f=107&t=306585

This is basically fine as is - I just have a few suggestions and requests - but it does need an entry in the Makefile otherwise it won't get built (alphabetical order applies there as well).

2021-03-12 08:47 UTC, pelwell commented on arch/arm/boot/dts/overlays/README
> +Params: gpio                    GPIO pin connected to the LED (default 19)
The active_low parameter requires an entry here.

2021-03-12 08:47 UTC, pelwell commented on arch/arm/boot/dts/overlays/gpio-led-overlay.dts
> +			pin_state: led_pins@0 {
I suggest you make the node "address" match the default gpio number, both for practical reasons and for appearances.

2021-03-12 08:47 UTC, pelwell commented on arch/arm/boot/dts/overlays/gpio-led-overlay.dts
> +
Since you'll be making other changes here, I don't think we need two blank lines.

2021-03-12 08:47 UTC, pelwell commented on arch/arm/boot/dts/overlays/gpio-led-overlay.dts
> +			                linux,default-trigger = "none";
Wouldn't `default-on` be a more useful default?

2021-03-14 01:41 UTC, agordon commented
Hi,
Thanks for the feedback, I updated the PR, except changing the default trigger to 'default-on' - I'm not sure about that - do we want to force users to turn on LEDs as default?

2021-03-14 20:14 UTC, pelwell commented
It still needs a Makefile entry, but I'll accept the `none` trigger.

2021-03-15 08:45 UTC, merged