dtoverlays: Add overlay for cap1106 capacitive touch sensor
raspberrypi/linux pull request #4442
Opened 2021-07-08 20:35 UTC by Mr-Bossman

Tested works on rpi3, alert pin being pin 4

2021-07-09 09:03 UTC, pelwell requested changes
This is two PRs in one - the overlay PR belongs here, but the driver change should be sent to the Linux kernel devs.

The overlay looks largely OK, but it's lacking entries in the README and Makefile, and the driver is not enabled in our defconfigs so most people would be unable to make use of it.

2021-07-09 09:03 UTC, pelwell commented on drivers/input/keyboard/cap11xx.c
> +	{ "cap1106", CAP1206 },
`"cap1206"`?

2021-07-09 09:03 UTC, pelwell commented on drivers/input/keyboard/cap11xx.c
> +		if (cap->product_id != 0x67)
This test would be better using either the index to the table (`!= CAP1206`) or by adding a flags field (`!(cap->flags & FLAGS_SENSOR_GAIN)`).

2021-07-09 09:03 UTC, pelwell commented on arch/arm/boot/dts/overlays/cap1106-overlay.dts
> +                                brcm,pull = <1>; /* none */
This doesn't make sense. Your interrupts flags above are 2 (`IRQ_TYPE_EDGE_FALLING`), a pull of `1` means pull _down_ (a falling-edge IRQ would normally require an pull up), and the comment says `none`.

2021-07-09 09:03 UTC, pelwell commented on arch/arm/boot/dts/overlays/cap1106-overlay.dts
> +                                pinctrl-0 = <&cap1106_pins>;
This is missing `pinctrl-names = "default";`

2021-07-09 16:12 UTC, pelwell reviewed
The overlay itself looks OK now, and the Makefile change. Your just missing a README entry - see #4444 for some guidance on that.

Before I merge this PR I'd also like a name and email address for the Signed-off-by: line in the commit message.

Can I assume that you would like `CONFIG_KEYBOARD_CAP11XX` adding to our standard configurations?

2021-07-09 16:39 UTC, Mr-Bossman commented
> Before I merge this PR I'd also like a name and email address for the Signed-off-by: line in the commit message.

How exactly do I do this... I'm not used to using GitHub for PRs. Do I add it to the git-commit-log description like on u-boot and the kernel?

> Can I assume that you would like CONFIG_KEYBOARD_CAP11XX adding to our standard configurations?

exactly.

> The overlay itself looks OK now, and the Makefile change. You're just missing a README entry - see #4444 for some guidance on that.

will do!

2021-07-09 16:50 UTC, pelwell commented
For the Signed-off-by, just write it in a comment and I can add it when merging, but normally it would be included at the end of your commit message.

2021-07-10 09:04 UTC, pelwell commented
The int_pin parameter wasn't documented and there were a few whitespace problems, but it's now in rpi-5.10.y along with a commit adding the required config setting.

2021-07-10 09:04 UTC, closed without merging