Pass V4L2_CID_MPEG_VIDEO_H264_MIN_QP/MAX_QP to bcm2835-v4l2-codec
raspberrypi/linux pull request #4705
Opened 2021-11-17 02:03 UTC by mdevaev

Following raspberrypi/linux#4704. This is necessary to set up quantization for variable bitrate to avoid video flickering.

2021-11-17 15:02 UTC, 6by9 requested changes

2021-11-17 15:02 UTC, 6by9 commented on drivers/staging/vc04_services/bcm2835-codec/bcm2835-v4l2-codec.c
> +				  0, 0x7FFFFFFF,
Max value for QP is 51.

2021-11-17 15:02 UTC, 6by9 commented on drivers/staging/vc04_services/bcm2835-codec/bcm2835-v4l2-codec.c
> +				  1, 0);
Max value is 51.
Shouldn't the default (last parameter) be 51 as well to allow rate control to use the full range? The firmware does special cases 0, so it will assume the defaults anyway, but setting 51 should also work.

Firmware defaults are min of 20, max 51, so those would be reasonable values to adopt.

2021-11-17 20:48 UTC, mdevaev commented on drivers/staging/vc04_services/bcm2835-codec/bcm2835-v4l2-codec.c
> +				  0, 0x7FFFFFFF,
Got it

2021-11-17 21:54 UTC, mdevaev commented on drivers/staging/vc04_services/bcm2835-codec/bcm2835-v4l2-codec.c
> +				  1, 0);
I changed the maximum and default values, if that's what you meant and I got it right for you.

2021-11-18 17:14 UTC, 6by9 approved these changes

2021-11-18 17:16 UTC, 6by9 commented
Thanks, that update was exactly what I was meaning.

I would like to give this a quick test, but fundamentally it looks good now.

Potentially a QP of 0 is going to be ignored as it is the default "not set" condition in the firmware, but I'm going to ignore that situation, and we'll change the min to being 1 if it becomes a problem.

2021-11-18 17:58 UTC, mdevaev commented
Great. I did a backport of this patch (with the previous default values) to 5.10.52 and it works great.

I would also like to add a separate patch to the ability to pass `V4L2_CID_MPEG_VIDEO_BITRATE_PEAK` as `MMAL_PARAMETER_VIDEO_ENCODE_PEAK_RATE` and maybe some others to keep the same behavior with my old implementation on MMAL.

There are three other parameters that were used in my implementation, but I took them from someone else's example and do not fully understand their meaning. These parameters are not set in the V4L2 interface. Are they needed? Because everything seems to work without them, but I have to ask to be sure.

```
MMAL_PARAMETER_NALUNITFORMAT = MMAL_VIDEO_NALUNITFORMAT_STARTCODES
MMAL_PARAMETER_MB_ROWS_PER_SLICE = 0
MMAL_PARAMETER_VIDEO_DROPPABLE_PFRAMES = MMAL_FALSE
```

2021-11-25 14:44 UTC, 6by9 commented
@pelwell I'm good with these. Any comments from you on this PR?

@mdevaev Generally please avoid adding extra discussion to a PR, but as a quick answer.

MMAL_PARAMETER_NALUNITFORMAT = MMAL_VIDEO_NALUNITFORMAT_STARTCODES
default. Memory says only MMAL_VIDEO_NALUNITFORMAT_FOURBYTEINTERLEAVELENGTH is the other format supported, which substitutes the start code for the length of the NAL (32bit value)

MMAL_PARAMETER_MB_ROWS_PER_SLICE = 0
default. Allows splitting the frame into multiple slices which can reduce latency but at the expense of bitrate.

MMAL_PARAMETER_VIDEO_DROPPABLE_PFRAMES = MMAL_FALSE
default. Setting it means that only every other P frame will be used as a reference frame. If a frame isn't used as a reference, there is no obligation to decode it, so it can be totally discarded without decoding if you want to fast forward in a stream.

2021-11-25 15:06 UTC, pelwell commented
Looks OK to me.

2021-11-25 15:07 UTC, merged

2021-11-25 18:47 UTC, mdevaev commented
@6by9 sorry and thanks for the answers