Update for Infineon MA120x0P Amplifier driver.
raspberrypi/linux pull request #5095
Opened 2022-07-15 15:34 UTC by Thenicolaibulow

Hi!

I've taken the liberty of making sure that our MA120x0p driver works with the latest kernel. 
I'd much appreciate if it were merged with the kernel. 

Thank you!

2022-07-15 16:10 UTC, pelwell requested changes

2022-07-15 16:10 UTC, pelwell commented on sound/soc/codecs/ma120x0p.h
> +// SPDX-License-Identifier: GPL-2.0-or-later
Unless the defines are being used in multiple places, the Linux kernel devs prefer to have them in the .c file, i.e. exactly as they were.

2022-07-15 16:10 UTC, pelwell commented on sound/soc/codecs/ma120x0p.c
> +static const SOC_VALUE_ENUM_SINGLE_DECL(pwr_mode_ctrl,
Huh? SOC_VALUE_ENUM_SINGLE_DECL should already include a `const`.

2022-07-15 16:10 UTC, pelwell commented on sound/soc/codecs/ma120x0p.c
> +//static const char * const audioproc_mute_text[] = {"Play", "Mute"};
It's bad enough leaving commented-out code/data lying around, but to introduce it already commented out is just wrong.

2022-07-15 16:10 UTC, pelwell commented on sound/soc/codecs/ma120x0p.c
> +/*
Maybe if this was your code I might allow ASCII art, but don't gratuitously add it to an existing driver.

2022-07-15 16:10 UTC, pelwell commented on sound/soc/codecs/ma120x0p.c
> -
Why delete this blank line - especially when you leave line 910?

2022-07-15 16:10 UTC, pelwell commented on sound/soc/codecs/ma120x0p.c
> +		ma_thr_db_ch0__a, ma_thr_db_ch1__a, 0, 0x0e, 0x4a, 1, ma120x0p_lim_tlv),
This driver was written to the 80-column limit. This may no longer be a hard requirement, but this cosmetic change is just pointless churn.

2022-07-15 16:10 UTC, pelwell commented on sound/soc/codecs/ma120x0p.c
> +			// This format is not supported by the Raspberry PI! - But is supported by the amplifier.
Why is this a useful thing to add to a Raspberry Pi kernel driver?

2022-07-15 16:10 UTC, pelwell commented on sound/soc/codecs/ma120x0p.c
> +		ma_audio_proc_limiterenable__a, ma_audio_proc_limiterenable__mask, 0x40);
The original was more readable.

2022-07-15 16:10 UTC, pelwell commented on sound/soc/codecs/ma120x0p.c
> +		ma_audio_proc_attack__a,ma_audio_proc_attack__mask, 0x80);
Random deletion of whitespace that is required by the coding standard (and general readability).

2022-07-15 16:10 UTC, pelwell commented on sound/soc/codecs/ma120x0p.c
> +	if (ret != 0){
Missing space before the brace.

2022-07-15 16:10 UTC, pelwell commented on sound/soc/codecs/ma120x0p.c
> +		if (ret & 0x01){dev_info(component->dev, "Flying Capacitor Overvoltage Error\n");}
```
		if (ret & 0x01)
			dev_info(component->dev, "Flying Capacitor Overvoltage Error\n");
```
etc.

2022-07-15 16:10 UTC, pelwell commented on sound/soc/codecs/ma120x0p.c
> +		if (ret & 0x08){dev_info(component->dev, "Over temperature Warning\n");}
`Temperature` for consistency.

2022-07-15 16:10 UTC, pelwell commented on sound/soc/codecs/ma120x0p.c
> +    return IRQ_HANDLED;
Indentation should be by 1 TAB character per indent level.

2022-07-15 16:10 UTC, pelwell commented on sound/soc/codecs/ma120x0p.c
> +		"mute_gp",GPIOD_OUT_LOW);
Why?

2022-07-15 16:10 UTC, pelwell commented on sound/soc/codecs/ma120x0p.c
> +
Too many blank lines.

2022-07-15 16:10 UTC, pelwell commented on sound/soc/bcm/merus-amp.c
> +/*
What does this dedicated driver offer over the support in rpi-simple-soundcard.c, other than commented out code and poor indentation?

2022-07-16 09:28 UTC, AMuszkat commented
@pelwell please reject this pull request. We'll try again with the proper code. merus-amp sound card sholdn't be added.

2022-07-16 11:36 UTC, closed without merging